### ISSUE TITLE
png opacity error

### ISSUE THREAD

**Issue by gejoreni** [timurnurutdinov/Framer-Inventory#24]
When you change the opacity of an image from 1 to 0, it also changed the size of that object.

**Comment by timurnurutdinov** [comment]
Confirmed. I'll figure out a fix soon.

As a temporary solution I can suggest toggle visibility rather than use opacity. Actually this error depends on Sketch bug: try exporting a png from a layer with 0 opacity. Sketch produces an image with unexpected size so does Framer Inventory.

**Comment by gejoreni** [comment]
thanks!

**Comment by timurnurutdinov** [comment]
Please, download new version of Framer Inventory and test in on your file.

**Comment by gejoreni** [comment]
RESOLVED! thanks
