### ISSUE TITLE
Causing Sketch app to lag

### ISSUE THREAD

**Issue by didacus** [timurnurutdinov/Framer-Inventory#56]
I am not sure someone can replicate this. Having the plugin active will cause lag to interactions on Sketch (a delay on selections for example).  Can anyone confirm this?

**Comment by timurnurutdinov** [comment]
Framer Inventory uses async methods to quick-check current selection and predict the output for Framer, so yes, it needs some computing power but it should not cause lags.

Can you try disabling other plugins and test it with only Framer Inventory enabled? If it still causes lags, share your mac model and I will check!

**Comment by timurnurutdinov** [comment]
Should be fixed with v3.3.0 release: https://github.com/timurnurutdinov/Framer-Inventory-for-Sketch/releases/tag/v3.3.0
