### ISSUE TITLE
Stopped working in Sketch v49

### ISSUE THREAD

**Issue by NamDang311** [timurnurutdinov/Framer-Inventory#57]
As mentioned, when pressing Export Layer, expect image to be exported to image folder in Framer. But in Sketch v49, its broken and only code being exported to clipboard.

**Comment by timurnurutdinov** [comment]
Hi, thanks for reporting! 
Problem is confirmed, looking for solution. Hope, I will publish an update in a couple of days.

**Comment by NamDang311** [comment]
The problem has been fixed in the lastest release. Thanks for the quick support.
